package agenda_hibernate.modelo;
// Generated 28/09/2015 18:32:22 by Hibernate Tools 4.3.1




/**
 * Noticias generated by hbm2java
 */
public class Noticias  implements java.io.Serializable {


     private int id;
     private Usuarios usuarios;
     private String titular;
     private String texto;
     private String fecha;

    public Noticias() {
    }

	
    public Noticias(int id) {
        this.id = id;
    }
    public Noticias(int id, Usuarios usuarios, String titular, String texto, String fecha) {
       this.id = id;
       this.usuarios = usuarios;
       this.titular = titular;
       this.texto = texto;
       this.fecha = fecha;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Usuarios getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Usuarios usuarios) {
        this.usuarios = usuarios;
    }
    public String getTitular() {
        return this.titular;
    }
    
    public void setTitular(String titular) {
        this.titular = titular;
    }
    public String getTexto() {
        return this.texto;
    }
    
    public void setTexto(String texto) {
        this.texto = texto;
    }
    public String getFecha() {
        return this.fecha;
    }
    
    public void setFecha(String fecha) {
        this.fecha = fecha;
    }




}


